/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.md.Tekwill.ui;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import com.mycompany.mavenproject1.md.Tekwill.dao.EmployeeDao;
import javax.swing.table.DefaultTableModel;
import com.mycompany.mavenproject1.md.Tekwill.domain.Department;
import com.mycompany.mavenproject1.md.Tekwill.exceptions.EmployeeException;
import com.mycompany.mavenproject1.md.Tekwill.exceptions.EmployeeExceptionChecker;

import com.mycompany.mavenproject1.md.Tekwill.service.EmployeeService;
import com.mycompany.mavenproject1.md.Tekwill.domain.Employee;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;


/**
 *
 * @author super
 */
public class NewJFrame extends javax.swing.JFrame {
    public static boolean isNumeric(String str) {
            if(str.length()==0){
            return false;}
            
            for(int i=0; i<str.length(); i++){
                if(str.charAt(i)<='9' && str.charAt(i)>='0'){
                continue;
                }
                return false;
            }
            return true;
    }   
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    EmployeeService employeeService = new EmployeeService();
    //EmployeeDao employeeDao = new EmployeeDao();
    Department[] departmentsArr = employeeService.getDepartments();
    
   DefaultTableModel model=new DefaultTableModel(
    new Object [][] {
    
    },
    new String [] {
        "ID", "Name", "Last Name", "Department"
    }
);
    
    void newTableModel(){
        
        Employee[] employees = employeeService.getArr();
        model.setRowCount(0);
        for(int i=0; i<employees.length; i++){
            Employee employee = employees[i];
            if(employee!=null){
                model.addRow( new Object[]{ employee.getId(), employee.getName(), employee.getLastName(), employee.getDepartment().getName() }  );
            }
        }
        
    }
    
    void tableUpdate(int id, String name, String lastName, String department){
        
        for(int i=0; i<model.getRowCount(); i++){
            if( Integer.valueOf( String.valueOf(model.getValueAt(i, 0))  )==id){
                model.setValueAt(name, i, 1);
                model.setValueAt(lastName, i, 2);
                model.setValueAt(department, i, 3);
                return;
            }
        }
        
        
    }
    
    void tableCreate(Employee employee){
         model.addRow( new Object[]{ employee.getId(), employee.getName(), employee.getLastName(), employee.getDepartment().getName() }  );
    }
    
    void tableDelete(int id){
        for(int i=0; i<model.getRowCount(); i++){
            if( Integer.valueOf(String.valueOf(model.getValueAt(i, 0) ))==id ){
                model.removeRow(i);
                return;
            }
        }
    }
    
    
    int popUpRow = -1;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateDialog = new javax.swing.JDialog();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        updateComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        createDialog = new javax.swing.JDialog();
        cancelButton1 = new javax.swing.JButton();
        okButton1 = new javax.swing.JButton();
        nameField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastNameField1 = new javax.swing.JTextField();
        createComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        findDialog = new javax.swing.JDialog();
        cancelButton2 = new javax.swing.JButton();
        okButton2 = new javax.swing.JButton();
        idField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deleteDialog = new javax.swing.JDialog();
        cancelButton3 = new javax.swing.JButton();
        okButton3 = new javax.swing.JButton();
        idField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EmployeeExceptionDialog = new javax.swing.JDialog();
        EmployeeExceptionOKButton = new javax.swing.JToggleButton();
        EmployeeExceptionText = new javax.swing.JLabel();
        TablePopUpMenu = new javax.swing.JPopupMenu();
        Info = new javax.swing.JMenuItem();
        Update = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        findButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        cancelButton.setText("Cancel");

        okButton.setText("OK");

        jLabel1.setText("ID:");

        jLabel2.setText("Last Name:");

        jLabel6.setText("Name:");

        updateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Department:");

        javax.swing.GroupLayout updateDialogLayout = new javax.swing.GroupLayout(updateDialog.getContentPane());
        updateDialog.getContentPane().setLayout(updateDialogLayout);
        updateDialogLayout.setHorizontalGroup(
            updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(updateDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(updateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateDialogLayout.setVerticalGroup(
            updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        cancelButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                updateDialog.setVisible(false);
            }
        });
        okButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                if( ! isNumeric(idField.getText()) ){
                    updateDialog.setVisible(false);
                    return;
                }
                int id =Integer.valueOf( idField.getText() );
                String name = nameField.getText();
                String lastName=lastNameField.getText();
                String dep = (String) updateComboBox.getSelectedItem();

                try{
                    EmployeeExceptionChecker.checkInfo(name, lastName);
                    if(employeeService.update(id, name, lastName, dep)){
                        tableUpdate(id, name, lastName, dep);
                    }
                    //newTableModel();
                    updateDialog.setVisible(false);
                }
                catch(EmployeeException exception){
                    EmployeeExceptionDialog.setModal(true);
                    EmployeeExceptionDialog.setSize(280, 180);
                    EmployeeExceptionText.setText(exception.getMessage());
                    EmployeeExceptionDialog.setVisible(true);
                }

                //Employee employee = new Employee(name, lastName);

            }
        });
        String[] departmentsString = new String[departmentsArr.length ] ;
        for(int i=0; i<departmentsArr.length; i++){

            departmentsString[i] = departmentsArr[i].getName();

        }
        updateComboBox.setModel( new javax.swing.DefaultComboBoxModel<> (departmentsString) );

        cancelButton1.setText("Cancel");

        okButton1.setText("OK");

        jLabel4.setText("Name:");

        jLabel5.setText("Last Name:");

        createComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Department:");

        javax.swing.GroupLayout createDialogLayout = new javax.swing.GroupLayout(createDialog.getContentPane());
        createDialog.getContentPane().setLayout(createDialogLayout);
        createDialogLayout.setHorizontalGroup(
            createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(okButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(createDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(nameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(createComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createDialogLayout.setVerticalGroup(
            createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(createDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        cancelButton1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                createDialog.setVisible(false);
            }
        });
        okButton1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                String name = nameField1.getText();
                String lastName = lastNameField1.getText();
                String dep = (String)createComboBox.getSelectedItem();

                try{
                    EmployeeExceptionChecker.checkInfo(name, lastName);
                    Employee employee = new Employee(name, lastName);

                    for(int i=0; i<departmentsArr.length; i++){
                        if(departmentsArr[i].getName()==dep){
                            employee.setDepartment(departmentsArr[i]);
                            break;
                        }
                    }

                    if(employeeService.create(employee)){
                        tableCreate(employee);
                    }

                    //newTableModel();

                    createDialog.setVisible(false);
                }
                catch(EmployeeException exception){
                    EmployeeExceptionDialog.setModal(true);
                    EmployeeExceptionDialog.setSize(280, 180);
                    EmployeeExceptionText.setText(exception.getMessage());
                    EmployeeExceptionDialog.setVisible(true);
                }

            }
        });
        /*String[] departmentsString = new String[departmentsArr.length ] ;
        for(int i=0; i<departmentsArr.length; i++){

            departmentsString[i] = departmentsArr[i].getName();

        }*/
        createComboBox.setModel( new javax.swing.DefaultComboBoxModel<> (departmentsString) );

        cancelButton2.setText("Cancel");

        okButton2.setText("OK");

        jLabel7.setText("ID:");

        javax.swing.GroupLayout findDialogLayout = new javax.swing.GroupLayout(findDialog.getContentPane());
        findDialog.getContentPane().setLayout(findDialogLayout);
        findDialogLayout.setHorizontalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(findDialogLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        findDialogLayout.setVerticalGroup(
            findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findDialogLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(findDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        cancelButton2.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                findDialog.setVisible(false);
            }
        });
        okButton2.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){

                if( ! isNumeric(idField1.getText() ) ){
                    findDialog.setVisible(false);
                    return;
                }

                int id = parseInt(idField1.getText() );
                Employee employee = employeeService.read(id);
                if(employee != null){
                    String name=employee.getName();
                    String lastName = employee.getLastName();
                    String dep = employee.getDepartment().getName();
                    JOptionPane.showMessageDialog(null, "The employee with the specified id is:\n\tID: "+id+"\n\tName: "+name+"\n\tLast Name: "+lastName+"\n\tDepartment: "+dep);
                }
                else{
                    JOptionPane.showMessageDialog(null, "The employee with the specified id hasn't been found...");
                }

                findDialog.setVisible(false);
            }
        });

        cancelButton3.setText("Cancel");

        okButton3.setText("OK");

        jLabel8.setText("ID:");

        javax.swing.GroupLayout deleteDialogLayout = new javax.swing.GroupLayout(deleteDialog.getContentPane());
        deleteDialog.getContentPane().setLayout(deleteDialogLayout);
        deleteDialogLayout.setHorizontalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(okButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(deleteDialogLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(idField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteDialogLayout.setVerticalGroup(
            deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDialogLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(deleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        cancelButton3.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                deleteDialog.setVisible(false);
            }
        });
        okButton3.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){

                if( ! isNumeric(idField2.getText()) ){
                    deleteDialog.setVisible(false);
                    return;
                }

                int id = parseInt(idField2.getText() );

                employeeService.delete(id);

                //newTableModel();
                tableDelete(id);
                deleteDialog.setVisible(false);
            }
        });

        EmployeeExceptionOKButton.setText("OK");

        EmployeeExceptionText.setText("jLabel11");

        javax.swing.GroupLayout EmployeeExceptionDialogLayout = new javax.swing.GroupLayout(EmployeeExceptionDialog.getContentPane());
        EmployeeExceptionDialog.getContentPane().setLayout(EmployeeExceptionDialogLayout);
        EmployeeExceptionDialogLayout.setHorizontalGroup(
            EmployeeExceptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeExceptionDialogLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(EmployeeExceptionOKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EmployeeExceptionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeExceptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EmployeeExceptionDialogLayout.setVerticalGroup(
            EmployeeExceptionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeExceptionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeExceptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeExceptionOKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmployeeExceptionOKButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                EmployeeExceptionDialog.setVisible(false);
            }
        });

        Info.setText("jMenuItem1");
        TablePopUpMenu.add(Info);
        Info.setText("Info");
        int InfoRow = -1;
        //Update.setText("Update");
        Info.addActionListener( new ActionListener(){
            public void actionPerformed(ActionEvent e){
                //int x = TablePopUpMenu.getLocation().x;
                //int y = TablePopUpMenu.getLocation().y;
                //int row = jTable1.rowAtPoint( TablePopUpMenu.getLocation() );
                int row=popUpRow;
                String id = jTable1.getValueAt(row, 0).toString();

                findDialog.setModal(true);

                idField1.setText(id);
                okButton2.doClick();
                //deleteDialog.setSize(new Dimension(300, 200));
                //deleteDialog.setVisible(true);
            }
        }  );

        Update.setText("jMenuItem1");
        TablePopUpMenu.add(Update);
        Update.setText("Update");
        int UpdateRow = -1;
        Update.addActionListener( new ActionListener(){
            public void actionPerformed(ActionEvent e){
                //int x = TablePopUpMenu.getLocation().x;
                //int y = TablePopUpMenu.getLocation().y;
                //int row = jTable1.rowAtPoint( TablePopUpMenu.getLocation() );
                int row = popUpRow;
                String id = jTable1.getValueAt(row, 0).toString();
                updateDialog.setModal(true);

                idField.setText(id);
                lastNameField.setText("");
                nameField.setText("");

                updateDialog.setSize(new Dimension(350, 300));
                updateDialog.setVisible(true);
            }
        }  );

        Delete.setText("jMenuItem1");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        TablePopUpMenu.add(Delete);
        Delete.setText("Delete");
        //Update.setText("Update");
        int DeleteRow = -1;
        Delete.addActionListener( new ActionListener(){
            public void actionPerformed(ActionEvent e){
                //int x = TablePopUpMenu.getLocation().x;
                //int y = TablePopUpMenu.getLocation().y;
                //int row = jTable1.rowAtPoint( TablePopUpMenu.getLocation() );
                int row = popUpRow;
                String id = jTable1.getValueAt(row, 0).toString();

                deleteDialog.setModal(true);

                idField2.setText(id);
                okButton3.doClick();
                //deleteDialog.setSize(new Dimension(300, 200));
                //deleteDialog.setVisible(true);
            }
        }  );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.setModel(model);
        jTable1.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent me){
                if(SwingUtilities.isRightMouseButton(me)){
                    int row = jTable1.rowAtPoint(me.getPoint() );
                    popUpRow = row;
                    TablePopUpMenu.show(jTable1, me.getX(), me.getY());

                }
            }

        });

        createButton.setText("Create");

        findButton.setText("Find");

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(createButton)
                        .addGap(32, 32, 32)
                        .addComponent(editButton)
                        .addGap(42, 42, 42)
                        .addComponent(findButton)
                        .addGap(38, 38, 38)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(editButton)
                    .addComponent(findButton)
                    .addComponent(deleteButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        createButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                createDialog.setModal(true);

                nameField1.setText("");
                lastNameField1.setText("");

                createDialog.setSize(new Dimension(350, 300));
                createDialog.setVisible(true);
                //...
            }
        });
        findButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                findDialog.setModal(true);

                idField1.setText("");

                findDialog.setSize(new Dimension(300, 200));
                findDialog.setVisible(true);
            }
        });
        editButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                updateDialog.setModal(true);

                idField.setText("");
                lastNameField.setText("");
                nameField.setText("");

                updateDialog.setSize(new Dimension(350, 300));
                updateDialog.setVisible(true);
            }
        });
        deleteButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                deleteDialog.setModal(true);

                idField2.setText("");

                deleteDialog.setSize(new Dimension(300, 200));
                deleteDialog.setVisible(true);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Delete;
    private javax.swing.JDialog EmployeeExceptionDialog;
    private javax.swing.JToggleButton EmployeeExceptionOKButton;
    private javax.swing.JLabel EmployeeExceptionText;
    private javax.swing.JMenuItem Info;
    private javax.swing.JPopupMenu TablePopUpMenu;
    private javax.swing.JMenuItem Update;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JButton createButton;
    private javax.swing.JComboBox<String> createComboBox;
    private javax.swing.JDialog createDialog;
    private javax.swing.JButton deleteButton;
    private javax.swing.JDialog deleteDialog;
    private javax.swing.JButton editButton;
    private javax.swing.JButton findButton;
    private javax.swing.JDialog findDialog;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JTextField idField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField lastNameField1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    private javax.swing.JButton okButton3;
    private javax.swing.JComboBox<String> updateComboBox;
    private javax.swing.JDialog updateDialog;
    // End of variables declaration//GEN-END:variables
}
